#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Do you like debian?
db_input high feb/password || true
db_go

# Check their answer.
db_get feb/password

echo "Returned $RET"

