Document: feb
Title: Debian feb Manual
Author: <insert document author here>
Abstract: This manual describes what feb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/feb/feb.sgml.gz

Format: postscript
Files: /usr/share/doc/feb/feb.ps.gz

Format: text
Files: /usr/share/doc/feb/feb.text.gz

Format: HTML
Index: /usr/share/doc/feb/html/index.html
Files: /usr/share/doc/feb/html/*.html
