#!/bin/bash

# Source debconf library.
. /usr/share/debconf/confmodule

FULLNEWVERSION=$(cat /etc/feb/version)
NEWVERSION=${FULLNEWVERSION:0:3}

echo "New version ${FULLNEWVERSION}"

case "$1" in
	configure)
	chown -R tomcat7:tomcat7 /var/lib/tomcat7/solr
	chown tomcat7:tomcat7 /etc/feb/feb.properties
	chmod 600 /etc/feb/feb.properties

	if [ -z "$2" ]; then
		db_get feb/password
		password=$RET

		sudo -u postgres psql -c "CREATE USER feb WITH PASSWORD '$password'" >> instalacao_feb.log;
		sudo -u postgres psql -f /usr/share/FEB/schema.sql >> /tmp/instalacao_feb.log;
		sudo -u postgres psql federacao -f /usr/share/FEB/data.sql >> /tmp/instalacao_feb.log;

		sudo -u postgres psql federacao -c "UPDATE usuarios SET senha = MD5('$password') WHERE login = 'admin'";

		sed -i "s/password=.*/password=$password/g" /etc/feb/feb.properties
		
		
	else
		FULLOLDVERSION=$2
		OLDVERSION=${FULLOLDVERSION:0:3}
		if [ "$OLDVERSION" = "$NEWVERSION" ]; then
			echo "Same major-minor, no database change"
		else
			echo "Standard upgrade procedure..."
			echo "Upgrading from $OLDVERSION to $NEWVERSION"
			sudo -u postgres psql -f /usr/share/FEB/upgrade${OLDVERSION}to${NEWVERSION}
		fi
	fi

	# remove password from debconf
	db_reset feb/password

	if [ -f /etc/tomcat7/server.xml ]; then
		TOMCAT_CONFIG=/etc/tomcat7/server.xml
	else
		TOMCAT_CONFIG=/etc/tomcat6/server.xml
	fi

	# removing old configuration to avoid duplicate lines
	sed -i '/dded by FEB/d' /etc/apache2/sites-enabled/000-default
	sed -i '/JkMount \/feb/d' /etc/apache2/sites-enabled/000-default
	sed -i '/dded by FEB/d' ${TOMCAT_CONFIG}
	sed -i '/<Connector port="8009" protocol="AJP\/1.3"/d' ${TOMCAT_CONFIG}
	
	# adding new configuration
	echo "Configurando na porta 80..."
	cp /usr/share/FEB/workers.properties /etc/libapache2-mod-jk/workers.properties
	sed -i '/<\/VirtualHost/ i\
# added by FEB\
 JkMount /feb* worker1' /etc/apache2/sites-enabled/000-default
	sed -i '/<Service name="Catalina">/ a\
# added by FEB \
<Connector port="8009" protocol="AJP/1.3" redirectPort="8443" URIEncoding="UTF-8" />' ${TOMCAT_CONFIG}

	sudo service postgresql restart > instalacao_feb.log;
	if [ -f /etc/init.d/tomcat7 ]; then
		sudo /etc/init.d/tomcat7 restart
	else
		sudo /etc/init.d/tomcat6 restart
	fi
	sudo /etc/init.d/apache2 restart 
;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

